Dev
Mo1far/BugTracker pull request #3
Opened 2021-01-06 21:34 UTC by vapelavsky

Buttons with a little bit of magic
Admin can describe why he declined bug
Messages which set on UI/UX standards

2021-01-06 22:13 UTC, Mo1far requested changes

2021-01-06 22:13 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> +    await bot.edit_message_reply_markup(c.from_user.id, c.message.message_id, reply_markup='')
replace to cq.message.delete_reply_markup()

2021-01-06 22:13 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> +    await bot.edit_message_reply_markup(msg.chat.id, message_id=msg.message_id - 1, reply_markup='')
replace to cq.message.delete_reply_markup()

2021-01-06 22:13 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> +    await bot.edit_message_reply_markup(msg.chat.id, message_id=msg.message_id - 1, reply_markup='')
replace to cq.message.delete_reply_markup()

2021-01-06 22:13 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> +    await bot.edit_message_reply_markup(msg.chat.id, message_id=msg.message_id - 1, reply_markup='')
replace to cq.message.delete_reply_markup()

2021-01-06 22:13 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> +        @dp.message_handler(state=RegisterBug.wait_cause)
What? handler in another handler? How you can explain this?

2021-01-06 22:13 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> +            await state.set_data({'cause': msg.text})
It's useless, no?

2021-01-06 22:13 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> +            await bug.update(cause=data.get('cause')).apply()
useless ?

2021-01-06 22:13 UTC, Mo1far commented on bot/chains/register_bug/state.py
> +    wait_cause = State()
maybe rename to the more describing variable?

2021-01-06 22:13 UTC, Mo1far commented on db/models/bug.py
> +    @classmethod
overkill method
we can simply use User.get(id)

2021-01-07 14:12 UTC, Mo1far requested changes

2021-01-07 14:12 UTC, Mo1far commented on bot/chains/register_bug/state.py
> +    bug = State()
useless ?

2021-01-07 14:12 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> +    message = await state.get_data()
state_data in var message right? maybe rename to state_data, etc ?

2021-01-07 14:12 UTC, Mo1far commented on bot/chains/register_bug/handlers.py
> -    await cq.answer('Готово')
maybe we can send cq answer from the different decision?

2021-01-07 14:33 UTC, vapelavsky commented on bot/chains/register_bug/handlers.py
> -    await cq.answer('Готово')
Ты плюс с минусом перепутал, онгличанин

2021-01-07 19:29 UTC, Mo1far requested changes
rename variables and check state usage

2021-01-07 19:45 UTC, Mo1far approved these changes

2021-01-07 19:46 UTC, merged